export enum THEME_ACTION_TYPES {
  SET_THEME_NAME = "SET_THEME_NAME"
}

export enum EXPERTISE_ACTION_TYPES {
  FETCH_EXPERTISES = "FETCH_EXPERTISES",
  SET_STACKS_WITH_EXPERTISES = "SET_STACKS_WITH_EXPERTISES",
  SET_EXPERTISES_LOADING = "SET_EXPERTISES_LOADING",
  SET_EXPERTISES_NOT_LOADING = "SET_EXPERTISES_NOT_LOADING"
}

export enum PROJECT_ACTION_TYPES {
  FETCH_PROJECTS = "FETCH_PROJECTS",
  SET_PROJECTS_WITH_EXPERTISES = "SET_PROJECTS_WITH_EXPERTISES",
  SET_PROJECTS_LOADING = "SET_PROJECTS_LOADING",
  SET_PROJECTS_NOT_LOADING = "SET_PROJECTS_NOT_LOADING",
  FETCH_PROJECT = "FETCH_PROJECT",
  SET_PROJECT_WITH_EXPERTISES = "SET_PROJECT_WITH_EXPERTISES",
  SET_PROJECT_LOADING = "SET_PROJECT_LOADING",
  SET_PROJECT_NOT_LOADING = "SET_PROJECT_NOT_LOADING"
}
export enum BLOG_ACTION_TYPES {
  FETCH_BLOG_SUMMARIES = "FETCH_BLOG_DATA",
  SET_BLOG_SUMMARIES = "SET_BLOG_SUMMARIES",
  SET_BLOG_SUMMARIES_LOADING = "SET_BLOG_SUMMARIES_LOADING",
  SET_BLOG_SUMMARIES_NOT_LOADING = "SET_BLOG_SUMMARIES_NOT_LOADING",
  FETCH_BLOG_ARTICLES = "FETCH_BLOG_ARTICLES",
  SET_BLOG_ARTICLES = "SET_BLOG_ARTICLES",
  SET_BLOG_ARTICLES_LOADING = "SET_BLOG_ARTICLES_LOADING",
  SET_BLOG_ARTICLES_NOT_LOADING = "SET_BLOG_ARTICLES_NOT_LOADING"
}
